[package]
name = "tiangz-dbproxy-server"
version = "0.4.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "TiangZ DBProxy 的独立 TCP 服务"

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tiangz-dbproxy-core = { path = "../dbproxy-core" }
tiangz-dbproxy-protocol = { path = "../dbproxy-protocol" }
tiangz-dbproxy-storage = { path = "../dbproxy-storage" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tiangz-dbproxy-client = { path = "../dbproxy-client" }
