// Generated by tools/generate_typescript_protocol_lock.mjs. Do not edit.
export const DBPROXY_PROTOCOL_VERSION = 1;
export const DBPROXY_PROTOCOL_FINGERPRINT = "8037e5538b07c8a5fbfd0eea013bf3d1e798ad4c2306e8dbebc986ec365279a2";
