// Generated by tools/generate_typescript_protocol_lock.mjs. Do not edit.
export const DBPROXY_PROTOCOL_VERSION = 1;
export const DBPROXY_PROTOCOL_FINGERPRINT = "4e6705f9349e06a1b3403b3cc13a6c0c820ccb2076fc8442e33e4787cad154d0";
