// Generated by tools/generate_typescript_protocol_lock.mjs. Do not edit.
export const DBPROXY_PROTOCOL_VERSION = 2;
export const DBPROXY_PROTOCOL_FINGERPRINT = "affd104ec61b48af713241daf11b2b7ba08577673054ee9aea0ef3653dab8c68";
