import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const protoPath = path.join(root, "crates", "dbproxy-protocol", "proto", "dbproxy.proto");
const protocolSourcePath = path.join(root, "crates", "dbproxy-protocol", "src", "lib.rs");
const outputPath = path.join(root, "sdk", "typescript", "src", "protocol-lock.ts");
const proto = (await readFile(protoPath, "utf8")).replace(/\r\n?/g, "\n");
const protocolSource = await readFile(protocolSourcePath, "utf8");
const versionMatch = protocolSource.match(/pub const PROTOCOL_VERSION: u32 = (\d+);/);
if (!versionMatch) throw new Error(`Cannot find PROTOCOL_VERSION in ${protocolSourcePath}`);
const protocolVersion = versionMatch[1];
const fingerprint = createHash("sha256").update(proto).digest("hex");
const output = `// Generated by tools/generate_typescript_protocol_lock.mjs. Do not edit.\nexport const DBPROXY_PROTOCOL_VERSION = ${protocolVersion};\nexport const DBPROXY_PROTOCOL_FINGERPRINT = "${fingerprint}";\n`;

let current = "";
try {
  current = await readFile(outputPath, "utf8");
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}
if (current !== output) await writeFile(outputPath, output, "utf8");
