import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const protoPath = path.join(root, "crates", "dbproxy-protocol", "proto", "dbproxy.proto");
const outputPath = path.join(root, "sdk", "typescript", "src", "protocol-lock.ts");
const proto = await readFile(protoPath);
const fingerprint = createHash("sha256").update(proto).digest("hex");
const output = `// Generated by tools/generate_typescript_protocol_lock.mjs. Do not edit.\nexport const DBPROXY_PROTOCOL_VERSION = 1;\nexport const DBPROXY_PROTOCOL_FINGERPRINT = "${fingerprint}";\n`;

let current = "";
try {
  current = await readFile(outputPath, "utf8");
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}
if (current !== output) await writeFile(outputPath, output, "utf8");
